/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.LogicaBilletera;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimerson
 */
public class AdminFrame extends javax.swing.JFrame {
    private int botonXOriginal;
    private int botonYOriginal;
    
    
    /**
     * Creates new form AdminFrame
     */
    
    public AdminFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private LogicaBilletera logica;

public AdminFrame(LogicaBilletera logica) {
    this.logica = logica;
    initComponents();
    setLocationRelativeTo(null); // Centrar la ventana
    
    botonXOriginal = bCerrarSesion.getX();
    botonYOriginal = bCerrarSesion.getY();
    bCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    
    UsuarioValor.setText(String.valueOf(logica.getUsuarios().size()));

    int totalTransacciones = 0;
    double saldoGlobal = 0;

    for (Modelos.Usuario u : logica.getUsuarios()) {
        totalTransacciones += u.getHistorial().size();
        if (u.getCuenta() != null) {
            saldoGlobal += u.getCuenta().getSaldo();
        }
    }

    TransaccionesValor.setText(String.valueOf(totalTransacciones));
    SaldoValor.setText("$" + saldoGlobal);
}
private void animacionPulseHover(javax.swing.JLabel label) {
    javax.swing.Timer timer = new javax.swing.Timer(15, null);

    final int steps = 6;
    final int desplazamiento = 2; // movimiento suave (2 px)
    final int[] contador = {0};
    final boolean[] ida = {true};

    timer.addActionListener((e) -> {

        if (ida[0]) {
            label.setLocation(label.getX(), label.getY() - 1);
        } else {
            label.setLocation(label.getX(), label.getY() + 1);
        }

        contador[0]++;

        if (contador[0] >= steps) {
            ida[0] = !ida[0];
            contador[0] = 0;
        }
    });

    timer.start();

    // Guardar timer dentro del label para cancelarlo
    label.putClientProperty("hoverTimer", timer);
}

private void detenerPulse(javax.swing.JLabel label) {
    Object timerObj = label.getClientProperty("hoverTimer");
    if (timerObj instanceof javax.swing.Timer timer) {
        timer.stop();
        label.putClientProperty("hoverTimer", null);
        // devolver el botón a su posición original
        label.setLocation(botonXOriginal, botonYOriginal);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        UsuarioValor = new javax.swing.JLabel();
        TransaccionesValor = new javax.swing.JLabel();
        SaldoValor = new javax.swing.JLabel();
        bCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));
        jPanel1.setLayout(null);
        jPanel1.add(TituloLabel);
        TituloLabel.setBounds(268, 218, 60, 29);

        UsuarioValor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        UsuarioValor.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioValor.setText("0");
        jPanel1.add(UsuarioValor);
        UsuarioValor.setBounds(300, 70, 20, 40);

        TransaccionesValor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TransaccionesValor.setForeground(new java.awt.Color(255, 255, 255));
        TransaccionesValor.setText("0");
        jPanel1.add(TransaccionesValor);
        TransaccionesValor.setBounds(510, 70, 19, 40);

        SaldoValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SaldoValor.setForeground(new java.awt.Color(255, 255, 255));
        SaldoValor.setText("0");
        jPanel1.add(SaldoValor);
        SaldoValor.setBounds(689, 70, 110, 30);

        bCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Buttom cerrar sesion.png"))); // NOI18N
        bCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCerrarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCerrarSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCerrarSesionMouseReleased(evt);
            }
        });
        jPanel1.add(bCerrarSesion);
        bCerrarSesion.setBounds(30, 530, 170, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Ventana Administrador.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 1200, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMouseExited
        bCerrarSesion.setLocation(botonXOriginal, botonYOriginal);
    }//GEN-LAST:event_bCerrarSesionMouseExited

    private void bCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMousePressed
        bCerrarSesion.setLocation(botonXOriginal, botonYOriginal - 1);
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Deseas cerrar la sesion?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            new LoginFrame(logica).setVisible(true); // ✅ Reutiliza la misma instancia
            this.dispose();
    }
    }//GEN-LAST:event_bCerrarSesionMousePressed

    private void bCerrarSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMouseReleased
        // Vuelve al estado hover (levemente levantado)
    if (bCerrarSesion.getBounds().contains(evt.getPoint())) {
        // Sigue encima del botón
        bCerrarSesion.setLocation(botonXOriginal, botonYOriginal - 2);
    } else {
        // El mouse se fue mientras hacía clic
        bCerrarSesion.setLocation(botonXOriginal, botonYOriginal);
    }
    }//GEN-LAST:event_bCerrarSesionMouseReleased

    private void bCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCerrarSesionMouseEntered
        bCerrarSesion.setLocation(botonXOriginal, botonYOriginal - 2);
    }//GEN-LAST:event_bCerrarSesionMouseEntered

   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SaldoValor;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel TransaccionesValor;
    private javax.swing.JLabel UsuarioValor;
    private javax.swing.JLabel bCerrarSesion;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
