package Vistas;

import java.awt.Graphics2D;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Vistas.HomeFrame;

/**
 *
 * @author Keynner Ramos
 */
public class ConfirmacionTransaccionFrame extends javax.swing.JFrame {
    
    private HomeFrame homeFrame;
    private int mouseX, mouseY;
    
     public ConfirmacionTransaccionFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void cargarDatos(String usuarioDestino, double monto) {
    //lblMensaje.setText("✅ Transacción realizada con éxito");
    lblMonto.setText("$" + monto);
    lblUsuario.setText(usuarioDestino);

    LocalDateTime ahora = LocalDateTime.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    lblFecha.setText("Fecha de envío: " + ahora.format(formato));
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarJPEG = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();
        FondoCaptura = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(245, 422));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarJPEG.setText("Guardar JPEG");
        btnGuardarJPEG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJPEGActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarJPEG, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 110, -1));

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Transacción realizada con éxito");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setText("Monto enviado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        getContentPane().add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 145, 20));

        jLabel2.setText("Fecha de transferencia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 148, 20));

        jLabel3.setText("Destinario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 125, 20));

        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Captura Transferencia.png"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FondoCaptura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoCapturaMouseDragged(evt);
            }
        });
        FondoCaptura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoCapturaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout FondoCapturaLayout = new javax.swing.GroupLayout(FondoCaptura);
        FondoCaptura.setLayout(FondoCapturaLayout);
        FondoCapturaLayout.setHorizontalGroup(
            FondoCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        FondoCapturaLayout.setVerticalGroup(
            FondoCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(FondoCaptura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarJPEGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJPEGActionPerformed
    try {
    // Capturar toda la ventana (incluye fondo verde + panel blanco + textos)
    Window window = SwingUtilities.getWindowAncestor(FondoCaptura);

    BufferedImage imagen = new BufferedImage(
            window.getWidth(),
            window.getHeight(),
            BufferedImage.TYPE_INT_RGB
    );

    Graphics2D g2d = imagen.createGraphics();
    window.printAll(g2d);
    g2d.dispose();

    String rutaProyecto = System.getProperty("user.dir"); 
    String carpetaCapturas = rutaProyecto + File.separator + "captura de transacciones";

    // Crear carpeta si no existe
    File carpeta = new File(carpetaCapturas);
    if (!carpeta.exists()) {
        carpeta.mkdirs();
    }

    File archivo = new File(carpeta, "transaccion_" + System.currentTimeMillis() + ".jpeg");
    ImageIO.write(imagen, "jpeg", archivo);

    JOptionPane.showMessageDialog(this, 
        "Imagen guardada correctamente en:\n" + archivo.getAbsolutePath()
    );

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al guardar imagen: " + e.getMessage());
}

 // Codigo antiguo de capturas       
    /* try {
    BufferedImage imagen = new BufferedImage(FondoCaptura.getWidth(), FondoCaptura.getHeight(), BufferedImage.TYPE_INT_RGB);
    Graphics2D g2d = imagen.createGraphics();
    FondoCaptura.paint(g2d);
    g2d.dispose();

    String rutaProyecto = System.getProperty("user.dir"); // Ruta base del proyecto
    String carpetaCapturas = rutaProyecto + File.separator + "captura de transacciones";

    // Crear carpeta si no existe
    File carpeta = new File(carpetaCapturas);
    if (!carpeta.exists()) {
        carpeta.mkdirs();
    }

    File archivo = new File(carpeta, "transaccion_" + System.currentTimeMillis() + ".jpeg");
    ImageIO.write(imagen, "jpeg", archivo);

    JOptionPane.showMessageDialog(this, "Imagen guardada correctamente en:\n" + archivo.getAbsolutePath());
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error al guardar imagen: " + e.getMessage());
}

*/

    }//GEN-LAST:event_btnGuardarJPEGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   if (homeFrame != null) {
        // Si vienes desde HomeFrame, vuelve a ese mismo
        homeFrame.actualizarSaldo();  // opcional: refresca saldo por si cambió
        homeFrame.setVisible(true);
    }
    this.dispose(); // Cierra la ventana de confirmación                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FondoCapturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoCapturaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_FondoCapturaMousePressed

    private void FondoCapturaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoCapturaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_FondoCapturaMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmacionTransaccionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoCaptura;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JButton btnGuardarJPEG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
