package Vistas;

import java.awt.Graphics2D;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Vistas.HomeFrame;

/**
 *
 * @author Keynner Ramos
 */
public class ConfirmacionTransaccionFrame extends javax.swing.JFrame {
    
    private HomeFrame homeFrame;
    private int mouseX, mouseY;
    
     public ConfirmacionTransaccionFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void cargarDatos(String usuarioDestino, double monto) {
    //lblMensaje.setText("✅ Transacción realizada con éxito");
    lblMonto.setText("$" + monto);
    lblUsuario.setText(usuarioDestino);

    LocalDateTime ahora = LocalDateTime.now();
    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    lblFecha.setText("Fecha de envío: " + ahora.format(formato));
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarJPEG = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        Wallpaper = new javax.swing.JLabel();
        FondoCaptura = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarJPEG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bGuardarAsPDF.png"))); // NOI18N
        btnGuardarJPEG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarJPEGMousePressed(evt);
            }
        });
        getContentPane().add(btnGuardarJPEG, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 160, 70));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monto enviado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bCerrar.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 160, 70));

        lblMonto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("lorem");
        getContentPane().add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de transferencia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("lorem");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 330, 20));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Destinario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("lorem");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 125, 20));

        Wallpaper.setBackground(new java.awt.Color(221, 220, 192));
        Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/ConfirmacionFrame.png"))); // NOI18N
        getContentPane().add(Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        FondoCaptura.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FondoCapturaMouseDragged(evt);
            }
        });
        FondoCaptura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FondoCapturaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout FondoCapturaLayout = new javax.swing.GroupLayout(FondoCaptura);
        FondoCaptura.setLayout(FondoCapturaLayout);
        FondoCapturaLayout.setHorizontalGroup(
            FondoCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FondoCapturaLayout.setVerticalGroup(
            FondoCapturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(FondoCaptura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FondoCapturaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoCapturaMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_FondoCapturaMousePressed

    private void FondoCapturaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoCapturaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_FondoCapturaMouseDragged

    private void btnGuardarJPEGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarJPEGMousePressed
         try {
        // 1. Obtener el contenedor raíz (toda la ventana Swing)
        java.awt.Component root = javax.swing.SwingUtilities.getRoot(this);
        
        if (root == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No se pudo encontrar la ventana para capturar.");
            return;
        }

        int ancho = root.getWidth();
        int alto  = root.getHeight();

        if (ancho <= 0 || alto <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "La ventana aún no tiene tamaño válido para capturar.");
            return;
        }

        // 2. Crear la imagen con el tamaño de la ventana
        java.awt.image.BufferedImage imagen = new java.awt.image.BufferedImage(
                ancho,
                alto,
                java.awt.image.BufferedImage.TYPE_INT_ARGB // Soporta fondo transparente
        );

        java.awt.Graphics2D g2d = imagen.createGraphics();
        // Pinta TODO lo que está en la ventana (paneles, labels, botones, etc.)
        root.paintAll(g2d);
        g2d.dispose();

        // 3. Ruta de la carpeta dentro del proyecto
        String rutaProyecto = System.getProperty("user.dir");
        String carpetaCapturas = rutaProyecto + java.io.File.separator + "captura de transacciones";

        java.io.File carpeta = new java.io.File(carpetaCapturas);
        if (!carpeta.exists()) {
            carpeta.mkdirs();
        }

        // 4. Guardar la imagen con nombre único
        java.io.File archivo = new java.io.File(
                carpeta,
                "transaccion_" + System.currentTimeMillis() + ".png" // mejor PNG para transparencia
        );

        javax.imageio.ImageIO.write(imagen, "png", archivo);

        javax.swing.JOptionPane.showMessageDialog(this,
            "Imagen guardada correctamente en:\n" + archivo.getAbsolutePath()
        );

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al guardar imagen: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGuardarJPEGMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        if (homeFrame != null) {
        // Si vienes desde HomeFrame, vuelve a ese mismo
        homeFrame.actualizarSaldo();  // opcional: refresca saldo por si cambió
        homeFrame.setVisible(true);
    }
    this.dispose(); // Cierra la ventana de confirmación  
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionTransaccionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmacionTransaccionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoCaptura;
    private javax.swing.JLabel Wallpaper;
    private javax.swing.JLabel btnGuardarJPEG;
    private javax.swing.JLabel jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
