/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.Usuario;
import java.awt.Color;
import java.text.SimpleDateFormat;


/**
 *
 * @author Dimerson
 */
public class HistorialFrame extends javax.swing.JFrame {

    private Usuario usuario;
    private HomeFrame homeFrame;

public HistorialFrame(Usuario usuario, HomeFrame homeFrame) {
    this.usuario = usuario;
    this.homeFrame = homeFrame;
    initComponents();
    setLocationRelativeTo(null);
    mostrarHistorial();
    
    jPanel2.setOpaque(false);
    jPanel2.setBackground(new Color(0,0,0,0));

    // Hacer transparente el JScrollPane
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);
    jScrollPane1.setBorder(null);

    // Hacer transparente el JTextArea
    jTextArea1.setOpaque(false);
    jTextArea1.setBackground(new Color(0,0,0,0));
    jTextArea1.setBorder(null);
    jTextArea1.setForeground(Color.WHITE); // o el color que uses
    
}
private void mostrarHistorial() {

    // Creamos un "cuaderno" donde vamos a ir escribiendo todas las transacciones
    // Este cuaderno se llama StringBuilder y sirve para juntar texto fácilmente
    StringBuilder historial = new StringBuilder();

    // Creamos una herramienta que convierte la fecha en un texto legible
    SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

    // Recorremos cada transacción que tiene el usuario en su historial
    for (Modelos.Transaccion t : usuario.getHistorial()) {
        
        // Convertimos la fecha de la transacción a un texto bonito usando el formato
        String fechaFormateada = formatoFecha.format(t.getFecha());

        // Vamos agregando cada parte de la transacción al cuaderno:
        // 1. La fecha
        // 2. El tipo de movimiento (recarga, envío)
        // 3. El monto en dinero
        // 4. La descripción de lo que pasó
        historial.append(fechaFormateada)
                 .append(" | ")
                 .append(t.getTipo())
                 .append(" | $").append(t.getMonto())
                 .append(" | ").append(t.getDescripcion())
                 .append("\n");
    }

    // Mostramos todo el cuaderno en el cuadro de texto de la ventana,
    // para que el usuario pueda ver su historial completo.
    jTextArea1.setText(historial.toString());
}


/*private void mostrarHistorial() {
    StringBuilder historial = new StringBuilder();
    for (Modelos.Transaccion t : usuario.getHistorial()) {
        
        historial.append(t.getTipo())
                 .append(" | $").append(t.getMonto())
                 .append(" | ").append(t.getDescripcion())
                 .append("\n");
    } 

    jTextArea1.setText(historial.toString());
} */
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VolverBoton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        VolverBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bVolver.png"))); // NOI18N
        VolverBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverBotonMousePressed(evt);
            }
        });
        jPanel1.add(VolverBoton);
        VolverBoton.setBounds(220, 480, 160, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 80, 510, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Historial de Transacciones.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonMousePressed
        this.dispose();
        homeFrame.setVisible(true);
    }//GEN-LAST:event_VolverBotonMousePressed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
