/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.LogicaBilletera;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimerson
 */
public class HomeFrame extends javax.swing.JFrame {
    
    
    private Modelos.Usuario usuario;
    private LogicaBilletera logica;
    private int mouseX, mouseY;
    
     
  public HomeFrame(Modelos.Usuario usuario, LogicaBilletera logica) {
    this.usuario = usuario;
    this.logica = logica;
    initComponents();

    // Mostrar saludo personalizado
    BienvenidaLabel.setText("Bienvenido, " + usuario.getNombre());

    if (usuario.getCuenta() != null) {
        double saldo = usuario.getCuenta().getSaldo();
        SaldoLabel.setText(saldo >= 0 ? "Saldo: $" + saldo : "Saldo inválido.");
    } else {
        SaldoLabel.setText("Saldo: sin cuenta asociada.");
    }

    if (usuario.getRol().equalsIgnoreCase("admin")) {
        EnviarDineroBoton.setVisible(false);
        RecargarDineroBoton.setVisible(false);
        //HistorialBoton.setVisible(false);
    }

    setLocationRelativeTo(null); // Centrar ventana
}
  

  public void actualizarSaldo() {
    if (usuario.getCuenta() != null) {
        double saldo = usuario.getCuenta().getSaldo();
        SaldoLabel.setText("Saldo: $" + saldo);
    } else {
        SaldoLabel.setText("Saldo: sin cuenta asociada.");
    }
}
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BienvenidaLabel = new javax.swing.JLabel();
        RecargarDineroBoton = new javax.swing.JButton();
        EnviarDineroBoton = new javax.swing.JButton();
        SaldoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cancelar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 10, 24, 30);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(240, 20, 130, 60);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2025 Money Tress. Todos los derechos reservados.");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 580, 290, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cerrar-sesion.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3);
        jLabel3.setBounds(100, 90, 32, 32);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/historial.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4);
        jLabel4.setBounds(470, 90, 40, 40);

        BienvenidaLabel.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        BienvenidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidaLabel.setText("Bienvenido, usuario.");
        jPanel3.add(BienvenidaLabel);
        BienvenidaLabel.setBounds(180, 90, 230, 31);

        RecargarDineroBoton.setBackground(new java.awt.Color(255, 174, 0));
        RecargarDineroBoton.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        RecargarDineroBoton.setForeground(new java.awt.Color(255, 255, 255));
        RecargarDineroBoton.setText("Recargar");
        RecargarDineroBoton.setBorder(null);
        RecargarDineroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecargarDineroBotonActionPerformed(evt);
            }
        });
        jPanel3.add(RecargarDineroBoton);
        RecargarDineroBoton.setBounds(150, 415, 100, 35);

        EnviarDineroBoton.setBackground(new java.awt.Color(31, 114, 27));
        EnviarDineroBoton.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        EnviarDineroBoton.setForeground(new java.awt.Color(255, 255, 255));
        EnviarDineroBoton.setText("Enviar");
        EnviarDineroBoton.setBorder(null);
        EnviarDineroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarDineroBotonActionPerformed(evt);
            }
        });
        jPanel3.add(EnviarDineroBoton);
        EnviarDineroBoton.setBounds(359, 418, 110, 35);

        SaldoLabel.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        SaldoLabel.setForeground(new java.awt.Color(255, 255, 255));
        SaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaldoLabel.setText("Saldo:$");
        jPanel3.add(SaldoLabel);
        SaldoLabel.setBounds(210, 290, 190, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        jPanel3.add(jLabel6);
        jLabel6.setBounds(240, 150, 120, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Inicio.png"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecargarDineroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecargarDineroBotonActionPerformed
        new RecargaFrame(usuario, logica, this).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_RecargarDineroBotonActionPerformed

    private void EnviarDineroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarDineroBotonActionPerformed
        new TransferenciaFrame(usuario, logica, this).setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_EnviarDineroBotonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Deseas cerrar el programa?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra el programa
        }
        // Si elige NO, simplemente no pasa nada
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Deseas cerrar la sesion?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            new LoginFrame(logica).setVisible(true); // ✅ Reutiliza la misma instancia
            this.dispose();
        }
        // Si elige NO, simplemente no pasa nada
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new HistorialFrame(usuario, this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
    }//GEN-LAST:event_formMouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
    mouseX = evt.getX();
    mouseY = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
    int x = evt.getXOnScreen();
    int y = evt.getYOnScreen();
    setLocation(x - mouseX, y - mouseY);  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidaLabel;
    private javax.swing.JButton EnviarDineroBoton;
    private javax.swing.JButton RecargarDineroBoton;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
