/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.LogicaBilletera;

/**
 *
 * @author Dimerson
 */
public class HomeFrame extends javax.swing.JFrame {
    
    
    private Modelos.Usuario usuario;
     
    public HomeFrame(Modelos.Usuario usuario) {
    this.usuario = usuario;
    initComponents();
         
        // Mostrar saludo personalizado
        BienvenidaLabel.setText("Bienvenido, " + usuario.getNombre());

        // Mostrar saldo si tiene cuenta, o mensaje alternativo
        if (usuario.getCuenta() != null) {
            double saldo = usuario.getCuenta().getSaldo();
            if (saldo >= 0) {
                SaldoLabel.setText("Saldo: $" + saldo);
            } else {
                SaldoLabel.setText("Saldo inválido.");
            }
        } else {
            SaldoLabel.setText("Saldo: sin cuenta asociada.");
        }

        // Ocultar botones si el usuario es admin
        if (usuario.getRol().equalsIgnoreCase("admin")) {
            EnviarDineroBoton.setVisible(false);
            RecargarDineroBoton.setVisible(false);
            HistorialBoton.setVisible(false);
        }

        setLocationRelativeTo(null); // Centrar ventana
    }


    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BienvenidaLabel = new javax.swing.JLabel();
        SaldoLabel = new javax.swing.JLabel();
        RecargarDineroBoton = new javax.swing.JButton();
        EnviarDineroBoton = new javax.swing.JButton();
        HistorialBoton = new javax.swing.JButton();
        CerrarSesionBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BienvenidaLabel.setText("Bienvenido");

        SaldoLabel.setText("Saldo:$");

        RecargarDineroBoton.setText("Recargar");

        EnviarDineroBoton.setText("Enviar");
        EnviarDineroBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarDineroBotonActionPerformed(evt);
            }
        });

        HistorialBoton.setText("Ver Historial");

        CerrarSesionBoton.setText("CerrarSesion");
        CerrarSesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CerrarSesionBoton)
                    .addComponent(HistorialBoton)
                    .addComponent(EnviarDineroBoton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(RecargarDineroBoton)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(SaldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BienvenidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BienvenidaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaldoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecargarDineroBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnviarDineroBoton)
                .addGap(18, 18, 18)
                .addComponent(HistorialBoton)
                .addGap(18, 18, 18)
                .addComponent(CerrarSesionBoton)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarDineroBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarDineroBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnviarDineroBotonActionPerformed

    private void CerrarSesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionBotonActionPerformed
             new LoginFrame(new LogicaBilletera()).setVisible(true); // ✅ BIEN (pero crea nueva lógica)
                    this.dispose(); // cerrar sesión actual
       
    }//GEN-LAST:event_CerrarSesionBotonActionPerformed

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidaLabel;
    private javax.swing.JButton CerrarSesionBoton;
    private javax.swing.JButton EnviarDineroBoton;
    private javax.swing.JButton HistorialBoton;
    private javax.swing.JButton RecargarDineroBoton;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
