
package Vistas ; 

import javax.swing.JOptionPane;
import Logica.LogicaBilletera;
import Modelos.Usuario;
import Logica.UsuarioNoEncontradoException;
import Vistas.HomeFrame;

/**
 *
 * @author Dimerson
 */
public class LoginFrame extends javax.swing.JFrame {
    
    // Lógica compartida de la billetera
    private LogicaBilletera logica;
    
    private int mouseX, mouseY;
    
    private int botonXOriginal;
    private int botonYOriginal;

    // Constructor que recibe la lógica
    public LoginFrame(LogicaBilletera logica) {
        this.logica = logica;
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        
        // Establecer valor transparente para el fondo de los text field
        UsuarioText.setOpaque(false);
        UsuarioText.setBackground(new java.awt.Color(0, 0, 0, 0));
        ContraseñaText.setOpaque(false);
        ContraseñaText.setBackground(new java.awt.Color(0, 0, 0, 0));
        
        botonXOriginal = bIniciarSesion.getX();
        botonYOriginal = bIniciarSesion.getY();
        bIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        bIniciarSesion = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JTextField();
        ContraseñaText = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDominante = new javax.swing.JLabel();
        jPanelInicioSesion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cancelar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 0, 40, 50);

        bIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bIniciarSesion.png"))); // NOI18N
        bIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bIniciarSesionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bIniciarSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bIniciarSesionMouseReleased(evt);
            }
        });
        getContentPane().add(bIniciarSesion);
        bIniciarSesion.setBounds(230, 400, 160, 60);

        UsuarioText.setBackground(new java.awt.Color(207, 210, 176));
        UsuarioText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioText.setBorder(null);
        UsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextActionPerformed(evt);
            }
        });
        UsuarioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioTextKeyTyped(evt);
            }
        });
        getContentPane().add(UsuarioText);
        UsuarioText.setBounds(205, 250, 200, 40);

        ContraseñaText.setBackground(new java.awt.Color(219, 218, 187));
        ContraseñaText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ContraseñaText.setForeground(new java.awt.Color(255, 255, 255));
        ContraseñaText.setBorder(null);
        ContraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextActionPerformed(evt);
            }
        });
        getContentPane().add(ContraseñaText);
        ContraseñaText.setBounds(210, 350, 200, 40);

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 51));
        jLabel5.setText("Registrate aqui");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 460, 110, 17);

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   ¿No tienes cuenta?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 460, 120, 16);

        jLabelDominante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/LoginFrame.png"))); // NOI18N
        getContentPane().add(jLabelDominante);
        jLabelDominante.setBounds(0, 0, 600, 600);

        jPanelInicioSesion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelInicioSesion.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelInicioSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelInicioSesionMouseDragged(evt);
            }
        });
        jPanelInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelInicioSesionMousePressed(evt);
            }
        });
        jPanelInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelInicioSesion);
        jPanelInicioSesion.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextActionPerformed

    private void ContraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextActionPerformed

    private void UsuarioTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioTextKeyTyped
                    char c = evt.getKeyChar();
    String textoActual = UsuarioText.getText();

    // 1. Permitir teclas de control (borrar, flechas, enter, etc.)
    if (Character.isISOControl(c)) {
        return;
    }

    // 2. Permitir números siempre (para documento)
    if (Character.isDigit(c)) {
        return;
    }

    // 3. Permitir SOLO la palabra "admin" como excepción
    if (Character.isLetter(c)) {
        String posible = textoActual + c;
        String posibleLower = posible.toLowerCase();

        // Permitir ir escribiendo: "a", "ad", "adm", "admi", "admin"
        if ("admin".startsWith(posibleLower)) {
            return;
        }
    }

    // 4. Si llegó aquí, bloquear cualquier otra cosa
    evt.consume();
    getToolkit().beep();
    JOptionPane.showMessageDialog(this, "Solo se permiten números.");                                                     
                        /*char c = evt.getKeyChar();

    // Permitir letras y espacios
    if (Character.isLetter(c) || Character.isWhitespace(c)) {
        return;
    }

    // Permitir teclas de control como borrar (backspace), flechas, etc.
    if (Character.isISOControl(c)) {
        return;
    }

    // Si no es letra, espacio ni tecla de control, no permitir
    evt.consume();
    getToolkit().beep();
    JOptionPane.showMessageDialog(this, "Solo se permiten letras.");     
*/
    }//GEN-LAST:event_UsuarioTextKeyTyped

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    new RegistroFrame(logica).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    int confirmacion = JOptionPane.showConfirmDialog(
    null,
    "¿Deseas cerrar el programa?",
    "Confirmación",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE
);

if (confirmacion == JOptionPane.YES_OPTION) {
    System.exit(0); // Cierra el programa
}
// Si elige NO, simplemente no pasa nada

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanelInicioSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioSesionMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanelInicioSesionMousePressed

    private void jPanelInicioSesionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioSesionMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanelInicioSesionMouseDragged

    private void bIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarSesionMouseEntered
        bIniciarSesion.setLocation(botonXOriginal, botonYOriginal - 2);
    }//GEN-LAST:event_bIniciarSesionMouseEntered

    private void bIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarSesionMouseExited
        bIniciarSesion.setLocation(botonXOriginal, botonYOriginal);
    }//GEN-LAST:event_bIniciarSesionMouseExited

    private void bIniciarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarSesionMousePressed
      bIniciarSesion.setLocation(botonXOriginal, botonYOriginal - 1);

    String identificador = UsuarioText.getText().trim(); // documento o "admin"
    String clave = new String(ContraseñaText.getPassword());

    if (identificador.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo documento / usuario admin no puede estar vacío.");
        return;
    }
    if (clave.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo contraseña no puede estar vacío.");
        return;
    }
    if (clave.length() < 6) {
        JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
        return;
    }
    if (!clave.matches(".*[a-zA-Z].*") || !clave.matches(".*\\d.*")) {
        JOptionPane.showMessageDialog(this, "La contraseña debe contener letras y números.");
        return;
    }

    try {
        Usuario u = logica.login(identificador, clave);

        if (u.getRol().equalsIgnoreCase("admin")) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido! " + u.getNombre());
            new AdminFrame(logica).setVisible(true); // Panel de administrador
            this.dispose();
        } else {
            new HomeFrame(u, logica).setVisible(true); // Usuario normal
        }
        this.dispose();

    } catch (UsuarioNoEncontradoException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
        /*  bIniciarSesion.setLocation(botonXOriginal, botonYOriginal - 1);
        String usuario = UsuarioText.getText().trim();
String clave = new String(ContraseñaText.getPassword());

if (usuario.isEmpty()) {
    JOptionPane.showMessageDialog(this, "El campo usuario no puede estar vacío.");
    return;
}
if (clave.isEmpty()) {
    JOptionPane.showMessageDialog(this, "El campo contraseña no puede estar vacío.");
    return;
}
if (clave.length() < 6) {
    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
    return;
}
if (!clave.matches(".*[a-zA-Z].*") || !clave.matches(".*\\d.*")) {
    JOptionPane.showMessageDialog(this, "La contraseña debe contener letras y números.");
    return;
}

try {
    Usuario u = logica.login(usuario, clave);
   if (u.getRol().equalsIgnoreCase("admin")) {
    JOptionPane.showMessageDialog(this, "¡Bienvenido! " + u.getNombre());
    new AdminFrame(logica).setVisible(true); // Abre el panel de administrador
    this.dispose(); // Cierra la ventana de login
    
}else {
    new HomeFrame(u, logica).setVisible(true); // 
    this.dispose();
}


    this.dispose();
} catch (UsuarioNoEncontradoException ex) {
    JOptionPane.showMessageDialog(this, ex.getMessage());
}
*/    
    }//GEN-LAST:event_bIniciarSesionMousePressed

    private void bIniciarSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bIniciarSesionMouseReleased
        if (bIniciarSesion.getBounds().contains(evt.getPoint())) {
        // Sigue encima del botón
        bIniciarSesion.setLocation(botonXOriginal, botonYOriginal - 2);
    } else {
        // El mouse se fue mientras hacía clic
        bIniciarSesion.setLocation(botonXOriginal, botonYOriginal);
    }
    }//GEN-LAST:event_bIniciarSesionMouseReleased



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraseñaText;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JLabel bIniciarSesion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDominante;
    private javax.swing.JPanel jPanelInicioSesion;
    // End of variables declaration//GEN-END:variables

}