
package Vistas ; 

import javax.swing.JOptionPane;
import Logica.LogicaBilletera;
import Modelos.Usuario;
import Logica.UsuarioNoEncontradoException;
import Vistas.HomeFrame;

/**
 *
 * @author Dimerson
 */
public class LoginFrame extends javax.swing.JFrame {

    // Lógica compartida de la billetera
    private LogicaBilletera logica;
    private int mouseX, mouseY;


    // Constructor que recibe la lógica
    public LoginFrame(LogicaBilletera logica) {
        this.logica = logica;
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UsuarioLabel = new javax.swing.JLabel();
        UsuarioLabel1 = new javax.swing.JLabel();
        ContraseñaText = new javax.swing.JPasswordField();
        UsuarioText = new javax.swing.JTextField();
        TituloLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IngresarBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelDominante = new javax.swing.JLabel();
        jPanelInicioSesion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 600));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Money");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 30, 150, 50);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setText("Money");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 30, 150, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        UsuarioLabel.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        UsuarioLabel.setText("Usuario:");

        UsuarioLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        UsuarioLabel1.setText("Contraseña:");

        ContraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextActionPerformed(evt);
            }
        });

        UsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextActionPerformed(evt);
            }
        });
        UsuarioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioTextKeyTyped(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Roboto Thin", 2, 36)); // NOI18N
        TituloLabel.setText("Iniciar Sesion");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        IngresarBoton.setText("Iniciar Sesion");
        IngresarBoton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IngresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("¿No tienes cuenta?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Registrate aqui");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(IngresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(TituloLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsuarioLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaText, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(IngresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(110, 160, 370, 390);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2025 Money Tress. Todos los derechos reservados.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 580, 290, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cancelar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(560, 10, 24, 30);

        jLabelDominante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Fondo00.png"))); // NOI18N
        getContentPane().add(jLabelDominante);
        jLabelDominante.setBounds(0, 0, 590, 600);

        jPanelInicioSesion.setBackground(new java.awt.Color(204, 204, 204));
        jPanelInicioSesion.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanelInicioSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelInicioSesionMouseDragged(evt);
            }
        });
        jPanelInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelInicioSesionMousePressed(evt);
            }
        });
        jPanelInicioSesion.setLayout(null);
        getContentPane().add(jPanelInicioSesion);
        jPanelInicioSesion.setBounds(0, 0, 590, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextActionPerformed

    private void IngresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBotonActionPerformed
     
   String usuario = UsuarioText.getText().trim();
String clave = new String(ContraseñaText.getPassword());

if (usuario.isEmpty()) {
    JOptionPane.showMessageDialog(this, "El campo usuario no puede estar vacío.");
    return;
}
if (clave.isEmpty()) {
    JOptionPane.showMessageDialog(this, "El campo contraseña no puede estar vacío.");
    return;
}
if (clave.length() < 6) {
    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
    return;
}
if (!clave.matches(".*[a-zA-Z].*") || !clave.matches(".*\\d.*")) {
    JOptionPane.showMessageDialog(this, "La contraseña debe contener letras y números.");
    return;
}

try {
    Usuario u = logica.login(usuario, clave);
    if (u.getRol().equalsIgnoreCase("admin")) {
        JOptionPane.showMessageDialog(this, "Bienvenido admin: " + u.getNombre());
        // Aquí puedes abrir una ventana PanelAdmin si lo deseas
    } else {
       new HomeFrame(u, logica).setVisible(true); // ✅ correcto

    }
    this.dispose();
} catch (UsuarioNoEncontradoException ex) {
    JOptionPane.showMessageDialog(this, ex.getMessage());
}

        
        
        
    }//GEN-LAST:event_IngresarBotonActionPerformed

    private void ContraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextActionPerformed

    private void UsuarioTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioTextKeyTyped
                              char c = evt.getKeyChar();
                    if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                       evt.consume();
                     getToolkit().beep();
                              JOptionPane.showMessageDialog(this, "Solo se permiten letras.");
}
    }//GEN-LAST:event_UsuarioTextKeyTyped

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    new RegistroFrame(logica).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
    int confirmacion = JOptionPane.showConfirmDialog(
    null,
    "¿Deseas cerrar el programa?",
    "Confirmación",
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE
);

if (confirmacion == JOptionPane.YES_OPTION) {
    System.exit(0); // Cierra el programa
}
// Si elige NO, simplemente no pasa nada

    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanelInicioSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioSesionMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanelInicioSesionMousePressed

    private void jPanelInicioSesionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInicioSesionMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanelInicioSesionMouseDragged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ContraseñaText;
    private javax.swing.JButton IngresarBoton;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JLabel UsuarioLabel1;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDominante;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}