
package Vistas ; 

import javax.swing.JOptionPane;
import Logica.LogicaBilletera;
import Modelos.Usuario;
import Logica.UsuarioNoEncontradoException;
import Vistas.HomeFrame;

/**
 *
 * @author Dimerson
 */
public class LoginFrame extends javax.swing.JFrame {

    // Lógica compartida de la billetera
    private LogicaBilletera logica;

    // Constructor que recibe la lógica
    public LoginFrame(LogicaBilletera logica) {
        this.logica = logica;
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        ContraseñaLabel = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JTextField();
        IngresarBoton = new javax.swing.JButton();
        RegistrarBoton = new javax.swing.JButton();
        ContraseñaText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloLabel.setText("Titulo");

        UsuarioLabel.setText("Usuario");

        ContraseñaLabel.setText("Contraseña");

        UsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextActionPerformed(evt);
            }
        });
        UsuarioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioTextKeyTyped(evt);
            }
        });

        IngresarBoton.setText("Ingresar");
        IngresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBotonActionPerformed(evt);
            }
        });

        RegistrarBoton.setText("Regristrar");
        RegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBotonActionPerformed(evt);
            }
        });

        ContraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ContraseñaLabel)
                                .addGap(155, 155, 155)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UsuarioText, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(ContraseñaText)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IngresarBoton)
                                    .addComponent(RegistrarBoton))
                                .addGap(94, 94, 94)))))
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioLabel)
                    .addComponent(UsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaLabel)
                    .addComponent(ContraseñaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(IngresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(RegistrarBoton)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextActionPerformed

    private void IngresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBotonActionPerformed
     
   String usuario = UsuarioText.getText().trim();
String clave = new String(ContraseñaText.getPassword());

if (usuario.isEmpty()) {
    JOptionPane.showMessageDialog(this, "El campo usuario no puede estar vacío.");
    return;
}
if (clave.isEmpty()) {
    JOptionPane.showMessageDialog(this, "El campo contraseña no puede estar vacío.");
    return;
}
if (clave.length() < 6) {
    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
    return;
}
if (!clave.matches(".*[a-zA-Z].*") || !clave.matches(".*\\d.*")) {
    JOptionPane.showMessageDialog(this, "La contraseña debe contener letras y números.");
    return;
}

try {
    Usuario u = logica.login(usuario, clave);
    if (u.getRol().equalsIgnoreCase("admin")) {
        JOptionPane.showMessageDialog(this, "Bienvenido admin: " + u.getNombre());
        // Aquí puedes abrir una ventana PanelAdmin si lo deseas
    } else {
       new HomeFrame(u, logica).setVisible(true); // ✅ correcto

    }
    this.dispose();
} catch (UsuarioNoEncontradoException ex) {
    JOptionPane.showMessageDialog(this, ex.getMessage());
}

        
        
        
    }//GEN-LAST:event_IngresarBotonActionPerformed

    private void RegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBotonActionPerformed
                  new RegistroFrame(logica).setVisible(true);
this.dispose();

    }//GEN-LAST:event_RegistrarBotonActionPerformed

    private void ContraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextActionPerformed

    private void UsuarioTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioTextKeyTyped
                              char c = evt.getKeyChar();
                    if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
                       evt.consume();
                     getToolkit().beep();
                              JOptionPane.showMessageDialog(this, "Solo se permiten letras.");
}
    }//GEN-LAST:event_UsuarioTextKeyTyped



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JPasswordField ContraseñaText;
    private javax.swing.JButton IngresarBoton;
    private javax.swing.JButton RegistrarBoton;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}