/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.LogicaBilletera;
import Modelos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimerson
 */
public class RecargaFrame extends javax.swing.JFrame {
    
  private Usuario usuario;
private LogicaBilletera logica;
private HomeFrame homeFrame;
private int mouseX, mouseY;
public RecargaFrame(Usuario usuario, LogicaBilletera logica, HomeFrame homeFrame) {
    this.usuario = usuario;
    this.logica = logica;
    this.homeFrame = homeFrame;
    initComponents();
    setLocationRelativeTo(null);
    MontoText.setOpaque(false);
    MontoText.setBackground(new java.awt.Color(0, 0, 0, 0));
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        RecargarBoton = new javax.swing.JLabel();
        VolverBoton = new javax.swing.JLabel();
        MontoText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        RecargarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bDepositar.png"))); // NOI18N
        RecargarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RecargarBotonMousePressed(evt);
            }
        });
        jPanel2.add(RecargarBoton);
        RecargarBoton.setBounds(170, 270, 160, 70);

        VolverBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bVolver.png"))); // NOI18N
        VolverBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverBotonMousePressed(evt);
            }
        });
        jPanel2.add(VolverBoton);
        VolverBoton.setBounds(170, 340, 160, 70);

        MontoText.setBackground(new java.awt.Color(207, 210, 176));
        MontoText.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        MontoText.setForeground(new java.awt.Color(255, 255, 255));
        MontoText.setBorder(null);
        MontoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoTextActionPerformed(evt);
            }
        });
        MontoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MontoTextKeyTyped(evt);
            }
        });
        jPanel2.add(MontoText);
        MontoText.setBounds(140, 200, 250, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/RecargaFrame.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void MontoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MontoTextKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '.' && c != '\b') {
            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_MontoTextKeyTyped

    private void MontoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoTextActionPerformed

    private void RecargarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecargarBotonMousePressed
       String texto = MontoText.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un monto.");
            return;
        }

        if (!texto.matches("\\d+(\\.\\d{1,2})?")) {
            JOptionPane.showMessageDialog(this, "El monto debe ser un número válido (ej: 1000 o 1000.50).");
            return;
        }

        double monto = Double.parseDouble(texto);

        if (monto <= 0) {
            JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.");
            return;
        }

        logica.recargarSaldo(usuario, monto);
        JOptionPane.showMessageDialog(this, "Saldo recargado con éxito: $" + monto);
        homeFrame.actualizarSaldo();
        homeFrame.setVisible(true);

    }//GEN-LAST:event_RecargarBotonMousePressed

    private void VolverBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonMousePressed
        this.dispose();
        homeFrame.setVisible(true);
    }//GEN-LAST:event_VolverBotonMousePressed

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MontoText;
    private javax.swing.JLabel RecargarBoton;
    private javax.swing.JLabel VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
