/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;
import Logica.LogicaBilletera;
import Modelos.Usuario;
import Vistas.LoginFrame;
/**
 *
 * @author Dimerson
 */  


/**
 * Pantalla para registrar nuevos usuarios en la billetera virtual.
 * Incluye validaciones de entrada y navegación hacia LoginFrame.
 */
public class RegistroFrame extends javax.swing.JFrame {

    private LogicaBilletera logica; // Lógica compartida del sistema
    private int mouseX, mouseY;
    // Constructor que recibe la lógica de la billetera
    public RegistroFrame(LogicaBilletera logica) {
        this.logica = logica;
        initComponents();
        setLocationRelativeTo(null);
        
        NombreText.setOpaque(false);
        NombreText.setBackground(new java.awt.Color(0, 0, 0, 0));
        DocumentoText.setOpaque(false);
        DocumentoText.setBackground(new java.awt.Color(0, 0, 0, 0));
        UsuarioText.setOpaque(false);
        UsuarioText.setBackground(new java.awt.Color(0, 0, 0, 0));
        ContraseñaText.setOpaque(false);
        ContraseñaText.setBackground(new java.awt.Color(0, 0, 0, 0));
        ConfimarText.setOpaque(false);
        ConfimarText.setBackground(new java.awt.Color(0, 0, 0, 0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        RegistrarBoton = new javax.swing.JLabel();
        VolverBoton = new javax.swing.JLabel();
        NombreText = new javax.swing.JTextField();
        DocumentoText = new javax.swing.JTextField();
        UsuarioText = new javax.swing.JTextField();
        ContraseñaText = new javax.swing.JTextField();
        ConfimarText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cancelar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 0, 40, 40);

        RegistrarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bRegistrar.png"))); // NOI18N
        RegistrarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RegistrarBotonMousePressed(evt);
            }
        });
        jPanel1.add(RegistrarBoton);
        RegistrarBoton.setBounds(320, 490, 160, 70);

        VolverBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bVolver.png"))); // NOI18N
        VolverBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverBotonMousePressed(evt);
            }
        });
        jPanel1.add(VolverBoton);
        VolverBoton.setBounds(140, 490, 160, 70);

        NombreText.setBackground(new java.awt.Color(221, 220, 192));
        NombreText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        NombreText.setForeground(new java.awt.Color(255, 255, 255));
        NombreText.setBorder(null);
        NombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextActionPerformed(evt);
            }
        });
        NombreText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTextKeyTyped(evt);
            }
        });
        jPanel1.add(NombreText);
        NombreText.setBounds(140, 90, 340, 50);

        DocumentoText.setBackground(new java.awt.Color(221, 220, 192));
        DocumentoText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        DocumentoText.setForeground(new java.awt.Color(255, 255, 255));
        DocumentoText.setBorder(null);
        DocumentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentoTextActionPerformed(evt);
            }
        });
        DocumentoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DocumentoTextKeyTyped(evt);
            }
        });
        jPanel1.add(DocumentoText);
        DocumentoText.setBounds(140, 170, 340, 50);

        UsuarioText.setBackground(new java.awt.Color(221, 220, 192));
        UsuarioText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        UsuarioText.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioText.setBorder(null);
        UsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextActionPerformed(evt);
            }
        });
        UsuarioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioTextKeyTyped(evt);
            }
        });
        jPanel1.add(UsuarioText);
        UsuarioText.setBounds(140, 270, 340, 50);

        ContraseñaText.setBackground(new java.awt.Color(221, 220, 192));
        ContraseñaText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ContraseñaText.setForeground(new java.awt.Color(255, 255, 255));
        ContraseñaText.setBorder(null);
        ContraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaText);
        ContraseñaText.setBounds(140, 370, 340, 50);

        ConfimarText.setBackground(new java.awt.Color(221, 220, 192));
        ConfimarText.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        ConfimarText.setForeground(new java.awt.Color(255, 255, 255));
        ConfimarText.setBorder(null);
        jPanel1.add(ConfimarText);
        ConfimarText.setBounds(140, 430, 340, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/RegistrarFrame.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextActionPerformed

    private void NombreTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTextKeyTyped
                   char c = evt.getKeyChar();

// Permitir teclas de control como borrar, flechas, tabulador
             if (Character.isISOControl(c)) {
                     return;
}

// Solo permitir letras y espacios
         if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
          evt.consume();
           getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras en el nombre.");
}   
    }//GEN-LAST:event_NombreTextKeyTyped

    private void DocumentoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DocumentoTextKeyTyped
        char c = evt.getKeyChar();

// Permitir teclas de control como borrar, flechas, enter, etc.
if (Character.isISOControl(c)) {
    return;
}

// Solo permitir dígitos del 0 al 9
if (!Character.isDigit(c)) {
    evt.consume();
    getToolkit().beep();
    JOptionPane.showMessageDialog(this, "Solo se permiten números en el documento.");
}
    }//GEN-LAST:event_DocumentoTextKeyTyped

    private void UsuarioTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioTextKeyTyped
        char c = evt.getKeyChar();

// Permitir borrar, flechas, enter, etc.
if (Character.isISOControl(c)) {
    return;
}

// Permitir solo letras y números
if (!Character.isLetterOrDigit(c)) {
    evt.consume();
    getToolkit().beep();
    JOptionPane.showMessageDialog(this, "El usuario solo puede contener letras y números.");
}
    }//GEN-LAST:event_UsuarioTextKeyTyped

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Deseas cerrar el programa?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra el programa
        }
        // Si elige NO, simplemente no pasa nada
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void NombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTextActionPerformed

    private void UsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextActionPerformed

    private void DocumentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentoTextActionPerformed

    private void RegistrarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBotonMousePressed
        String nombre = NombreText.getText().trim();
        String documento = DocumentoText.getText().trim();
        String usuario = UsuarioText.getText().trim();
        String clave = ContraseñaText.getText().trim();
        String confirmar = ConfimarText.getText().trim();

        // Validaciones básicas
        if (nombre.isEmpty() || documento.isEmpty() || usuario.isEmpty() || clave.isEmpty() || confirmar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        if (clave.length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
            return;
        }

        if (!clave.matches(".*[a-zA-Z].*") || !clave.matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(this, "La contraseña debe contener letras y números.");
            return;
        }

        if (!clave.equals(confirmar)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }
        
            
            // Crear el usuario
            Usuario nuevo = new Usuario(nombre, usuario, clave, "cliente");
            nuevo.setDocumentoIdentidad(documento);   // 👈 AQUÍ guardamos el documento en el modelo

// Validar duplicado y registrar
            if (logica.registrarUsuario(nuevo)) {
            JOptionPane.showMessageDialog(this, 
            "Usuario registrado con éxito.\nAhora puedes iniciar sesión con tu documento de identidad.");
            new LoginFrame(logica).setVisible(true);
            this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe un usuario con ese nombre de cuenta.");
}
    }//GEN-LAST:event_RegistrarBotonMousePressed

    private void VolverBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonMousePressed
        new LoginFrame(logica).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverBotonMousePressed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfimarText;
    private javax.swing.JTextField ContraseñaText;
    private javax.swing.JTextField DocumentoText;
    private javax.swing.JTextField NombreText;
    private javax.swing.JLabel RegistrarBoton;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JLabel VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
