/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;
import Logica.LogicaBilletera;
import Modelos.Usuario;
import Vistas.LoginFrame;
/**
 *
 * @author Dimerson
 */  


/**
 * Pantalla para registrar nuevos usuarios en la billetera virtual.
 * Incluye validaciones de entrada y navegación hacia LoginFrame.
 */
public class RegistroFrame extends javax.swing.JFrame {

    private LogicaBilletera logica; // Lógica compartida del sistema
    private int mouseX, mouseY;
    // Constructor que recibe la lógica de la billetera
    public RegistroFrame(LogicaBilletera logica) {
        this.logica = logica;
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NombreText = new javax.swing.JTextField();
        DocumentoText = new javax.swing.JTextField();
        UsuarioText = new javax.swing.JTextField();
        ContraseñaText = new javax.swing.JTextField();
        ConfimarText = new javax.swing.JTextField();
        VolverBoton = new javax.swing.JButton();
        RegistrarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Registro");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 40, 210, 60);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cancelar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 10, 24, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2025 Money Tress. Todos los derechos reservados.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 580, 290, 16);

        NombreText.setBackground(new java.awt.Color(221, 220, 192));
        NombreText.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        NombreText.setBorder(null);
        NombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextActionPerformed(evt);
            }
        });
        NombreText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTextKeyTyped(evt);
            }
        });
        jPanel1.add(NombreText);
        NombreText.setBounds(130, 150, 340, 30);

        DocumentoText.setBackground(new java.awt.Color(221, 220, 192));
        DocumentoText.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        DocumentoText.setBorder(null);
        DocumentoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DocumentoTextKeyTyped(evt);
            }
        });
        jPanel1.add(DocumentoText);
        DocumentoText.setBounds(130, 210, 340, 30);

        UsuarioText.setBackground(new java.awt.Color(221, 220, 192));
        UsuarioText.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        UsuarioText.setBorder(null);
        UsuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextActionPerformed(evt);
            }
        });
        UsuarioText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UsuarioTextKeyTyped(evt);
            }
        });
        jPanel1.add(UsuarioText);
        UsuarioText.setBounds(130, 289, 340, 30);

        ContraseñaText.setBackground(new java.awt.Color(221, 220, 192));
        ContraseñaText.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ContraseñaText.setBorder(null);
        ContraseñaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTextActionPerformed(evt);
            }
        });
        jPanel1.add(ContraseñaText);
        ContraseñaText.setBounds(130, 375, 340, 30);

        ConfimarText.setBackground(new java.awt.Color(221, 220, 192));
        ConfimarText.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ConfimarText.setBorder(null);
        jPanel1.add(ConfimarText);
        ConfimarText.setBounds(130, 429, 340, 30);

        VolverBoton.setBackground(new java.awt.Color(217, 217, 217));
        VolverBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        VolverBoton.setForeground(new java.awt.Color(255, 255, 255));
        VolverBoton.setText("Volver");
        VolverBoton.setBorder(null);
        VolverBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverBotonActionPerformed(evt);
            }
        });
        jPanel1.add(VolverBoton);
        VolverBoton.setBounds(190, 495, 90, 33);

        RegistrarBoton.setBackground(new java.awt.Color(57, 196, 62));
        RegistrarBoton.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        RegistrarBoton.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarBoton.setText("Registrar");
        RegistrarBoton.setBorder(null);
        RegistrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarBoton);
        RegistrarBoton.setBounds(320, 498, 96, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Checkout.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContraseñaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTextActionPerformed

    private void NombreTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTextKeyTyped
                   char c = evt.getKeyChar();

// Permitir teclas de control como borrar, flechas, tabulador
             if (Character.isISOControl(c)) {
                     return;
}

// Solo permitir letras y espacios
         if (!Character.isLetter(c) && !Character.isWhitespace(c)) {
          evt.consume();
           getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Solo se permiten letras en el nombre.");
}   
    }//GEN-LAST:event_NombreTextKeyTyped

    private void DocumentoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DocumentoTextKeyTyped
        char c = evt.getKeyChar();

// Permitir teclas de control como borrar, flechas, enter, etc.
if (Character.isISOControl(c)) {
    return;
}

// Solo permitir dígitos del 0 al 9
if (!Character.isDigit(c)) {
    evt.consume();
    getToolkit().beep();
    JOptionPane.showMessageDialog(this, "Solo se permiten números en el documento.");
}
    }//GEN-LAST:event_DocumentoTextKeyTyped

    private void UsuarioTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioTextKeyTyped
        char c = evt.getKeyChar();

// Permitir borrar, flechas, enter, etc.
if (Character.isISOControl(c)) {
    return;
}

// Permitir solo letras y números
if (!Character.isLetterOrDigit(c)) {
    evt.consume();
    getToolkit().beep();
    JOptionPane.showMessageDialog(this, "El usuario solo puede contener letras y números.");
}
    }//GEN-LAST:event_UsuarioTextKeyTyped

    private void RegistrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBotonActionPerformed
        
    String nombre = NombreText.getText().trim();
    String documento = DocumentoText.getText().trim();
    String usuario = UsuarioText.getText().trim();
    String clave = ContraseñaText.getText().trim();
    String confirmar = ConfimarText.getText().trim();

    // Validaciones básicas
    if (nombre.isEmpty() || documento.isEmpty() || usuario.isEmpty() || clave.isEmpty() || confirmar.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        return;
    }

    if (clave.length() < 6) {
        JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
        return;
    }

    if (!clave.matches(".*[a-zA-Z].*") || !clave.matches(".*\\d.*")) {
        JOptionPane.showMessageDialog(this, "La contraseña debe contener letras y números.");
        return;
    }

    if (!clave.equals(confirmar)) {
        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
        return;
    }

    // Crear el usuario
    Usuario nuevo = new Usuario(nombre, usuario, clave, "cliente");

    // Validar duplicado y registrar
    if (logica.registrarUsuario(nuevo)) {
        JOptionPane.showMessageDialog(this, "Usuario registrado con éxito.");
        new LoginFrame(logica).setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Ya existe un usuario con ese nombre de cuenta.");
    }

       
    }//GEN-LAST:event_RegistrarBotonActionPerformed

    private void VolverBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverBotonActionPerformed
        new LoginFrame(logica).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverBotonActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Deseas cerrar el programa?",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra el programa
        }
        // Si elige NO, simplemente no pasa nada
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void NombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTextActionPerformed

    private void UsuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfimarText;
    private javax.swing.JTextField ContraseñaText;
    private javax.swing.JTextField DocumentoText;
    private javax.swing.JTextField NombreText;
    private javax.swing.JButton RegistrarBoton;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JButton VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
