/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.LogicaBilletera;
import Modelos.Usuario;
import javax.swing.JOptionPane;
import Vistas.ConfirmacionTransaccionFrame;
/**
 *
 * @author Dimerson
 */
public class TransferenciaFrame extends javax.swing.JFrame {

    private Usuario remitente;
    private LogicaBilletera logica;
    private HomeFrame homeFrame;
    private int mouseX, mouseY;

    public TransferenciaFrame(Usuario remitente, LogicaBilletera logica, HomeFrame homeFrame) {
    this.remitente = remitente;   // 👈 AHORA SÍ se inicializa
    this.logica = logica;
    this.homeFrame = homeFrame;
    initComponents();
    setLocationRelativeTo(null);
    
    MontoText.setOpaque(false);
    MontoText.setBackground(new java.awt.Color(0, 0, 0, 0));
    
    CuentaDestinoText.setOpaque(false);
    CuentaDestinoText.setBackground(new java.awt.Color(0, 0, 0, 0));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CuentaDestinoText = new javax.swing.JTextField();
        MontoText = new javax.swing.JTextField();
        EnviarBoton = new javax.swing.JLabel();
        VolverBoton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(null);

        CuentaDestinoText.setBackground(new java.awt.Color(207, 210, 176));
        CuentaDestinoText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        CuentaDestinoText.setForeground(new java.awt.Color(255, 255, 255));
        CuentaDestinoText.setBorder(null);
        CuentaDestinoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaDestinoTextActionPerformed(evt);
            }
        });
        jPanel1.add(CuentaDestinoText);
        CuentaDestinoText.setBounds(130, 290, 280, 50);

        MontoText.setBackground(new java.awt.Color(207, 210, 176));
        MontoText.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        MontoText.setForeground(new java.awt.Color(255, 255, 255));
        MontoText.setBorder(null);
        MontoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoTextActionPerformed(evt);
            }
        });
        jPanel1.add(MontoText);
        MontoText.setBounds(130, 200, 280, 50);

        EnviarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bEnviar (1).png"))); // NOI18N
        EnviarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EnviarBotonMousePressed(evt);
            }
        });
        jPanel1.add(EnviarBoton);
        EnviarBoton.setBounds(260, 350, 160, 70);

        VolverBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bVolver.png"))); // NOI18N
        VolverBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VolverBotonMousePressed(evt);
            }
        });
        jPanel1.add(VolverBoton);
        VolverBoton.setBounds(90, 350, 160, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/TransferenciaFrame.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void CuentaDestinoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaDestinoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentaDestinoTextActionPerformed

    private void MontoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoTextActionPerformed

    private void VolverBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBotonMousePressed
        this.dispose();            // Cierra Transferencia
        homeFrame.setVisible(true); // Regresa al Home
    }//GEN-LAST:event_VolverBotonMousePressed

    private void EnviarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarBotonMousePressed
        String cuentaDestino = CuentaDestinoText.getText().trim();
    String montoStr = MontoText.getText().trim();

    // Validación: campos vacíos
    if (cuentaDestino.isEmpty() || montoStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
        return;
    }

    // Validación: formato numérico del monto
    if (!montoStr.matches("\\d+(\\.\\d{1,2})?")) {
        JOptionPane.showMessageDialog(this, "Ingrese un monto válido (ej: 1000 o 1000.50).");
        return;
    }

    double monto = Double.parseDouble(montoStr);

    // Validación: monto positivo
    if (monto <= 0) {
        JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.");
        return;
    }

    // Validación: no enviar a sí mismo
    if (cuentaDestino.equals(remitente.getNumeroCuenta())) {
        JOptionPane.showMessageDialog(this, "No puedes transferirte dinero a ti mismo.");
        return;
    }

    // Validación: saldo suficiente
    double saldoDisponible = remitente.getCuenta().getSaldo();
    if (monto > saldoDisponible) {
        JOptionPane.showMessageDialog(this, "No tienes suficiente saldo para realizar esta transferencia.");
        return;
    }

    // Buscar usuario destino en la lista
    Usuario receptor = null;
    for (Usuario u : logica.getUsuarios()) {
        if (u.getNumeroCuenta().equals(cuentaDestino)) {
            receptor = u;
            break;
        }
    }

    // Validación: usuario destino existe
    if (receptor == null) {
        JOptionPane.showMessageDialog(this, "La cuenta destino no existe.");
        return;
    }

    // Realizar la transferencia
    double nuevoSaldoRemitente = saldoDisponible - monto;
    remitente.getCuenta().setSaldo(nuevoSaldoRemitente);

    double saldoReceptor = receptor.getCuenta().getSaldo();
    receptor.getCuenta().setSaldo(saldoReceptor + monto);
    
    // Registrar en historial
    remitente.getHistorial().add(new Modelos.Transaccion("Envío", monto, "Envío a " + cuentaDestino));
    receptor.getHistorial().add(new Modelos.Transaccion("Recibo", monto, "Recibido de " + remitente.getNumeroCuenta()));

    JOptionPane.showMessageDialog(this, "Transferencia exitosa de $" + monto + " a " + cuentaDestino);
    
    ConfirmacionTransaccionFrame confirmacion = new ConfirmacionTransaccionFrame();
    confirmacion.cargarDatos(cuentaDestino, monto);
    confirmacion.setVisible(true);

    // Actualizar saldo en pantalla de inicio
    homeFrame.actualizarSaldo();
    logica.guardarEstadoSistema();
    
    }//GEN-LAST:event_EnviarBotonMousePressed

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CuentaDestinoText;
    private javax.swing.JLabel EnviarBoton;
    private javax.swing.JTextField MontoText;
    private javax.swing.JLabel VolverBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
